#!/bin/bash
#PBS -q omp
#PBS -l ncpus=28
#PBS -l mem=115g
#PBS -l walltime=24:00:00
#  COMMENT
#  Tina ODAKA 06.03.2017
#  example for using datarmor with 'queue omp' in a personalised way
#  By default, if you use 'omp' it use 1 node with 2 openmp threads
#  here we show you example of it using 10 openmp threads (specify ncpus=10)
#  and it use 10g of memory in this example (specifly mem=10g)
#  and you can run max for 30 minutes with walltime setting
#  To optimised multi thread, you need to place a command 'omplace' before your 'exe'
#  Here, in this example, we suppose that your code 'exe' is compiled with
#  intel compiler.

# for the users who use gnu compiler, plz use omp.10g.gnu.pbs
#
# cd to the directory you submitted your job
cd $PBS_O_WORKDIR
qstat -f $PBS_JOBID

source /usr/share/Modules/3.2.10/init/bash
module load anaconda-py3.6/4.3.13

cd /appli/anaconda/3.6/bin
source activate pyticles_pp

echo $LD_LIBRARY_PATH


SCRIPT_PATH='/home2/datahome/lwang/Pyticles/Postprocessing/lu_postprocessing/Forward_Simulation/'
cd $SCRIPT_PATH

export PYTHONPATH=$HOME/home2/datahome/lwang/.conda/envs/pyti_conda/bin/python

logdir=/home2/datahome/lwang/Pyticles/logs
logfile=${logdir}/boxplot_cluster_vrt_ow.log
mkdir -p $logdir


date
python boxplot_clusters_vrt_ow.py >& $logfile

date



































